### ISSUE TITLE
V 1.1.0 Induces a fatal run-time error

### ISSUE THREAD

**Issue by SeriousSoftware** [vmunier/scalajs-scripts#14]
Requesting to a static endpoint defined by "GET /assets/*file controllers.Assets.versioned(path="/public", file: Asset)" results in a fatal run-time error.
Replay this error by cloning [Scala.js SPA Tutorial](https://github.com/amsterdam-scala/Sjs-SPA-tutorial) and bump  scalajsScripts from "1.0.0" to "1.1.0". A request to target/images/favicon.png will crash the server.

Work-around: Stay with 1.0.0.

**Comment by vmunier** [comment]
Yes, it is due to scalajs-scripts `v1.1.0` including Twirl `v1.3.0`, which is binary incompatible with `v1.2.x`. As you said, the best option is to keep using scalajs-scripts `v1.0.0` along with Play until a new version of Play comes out with Twirl `v1.3.0`. (Play `v2.5.10` is still using Twirl `v1.1.1`)

**Comment by vmunier** [comment]
* I updated the README.md to mention that Play users should use scalajs-scripts `v1.0.0` until Play upgrades to Twirl `v1.3.0`: https://github.com/vmunier/scalajs-scripts/commit/32e58b57d480090c7f4066bfaaab82c05b5e45fa.
* This Play framework PR includes twirl `v1.3.0`: https://github.com/playframework/playframework/pull/6691
