### ISSUE TITLE
add a way to disable jsdeps.js

### ISSUE THREAD

**Issue by schmitch** [vmunier/scalajs-scripts#7]
Hello, currently scalajs will always generate a "client-jsdeps.js" file which will be included by this play-scalajs-scripts.
However we don't want to use it, so could you make a boolean flag that we could exclude that file?

Oh I could do that aswell.

**Comment by vmunier** [comment]
It has been fixed in recent versions. Using scalajs-scripts `v1.0.0` along with sbt-web-scalajs `v1.0.1` do not include any `client-jsdeps.js` when the file is empty (which happens when there are no js dependencies).

Relevant lines of code from sbt-web-scalajs: https://github.com/vmunier/sbt-web-scalajs/blob/e14dc902cecefdf418c77c336166fdee7ce8f0e7/src/main/scala/webscalajs/WebScalaJS.scala#L121-L122)
